const CONFIG = {
    introTitle: 'Nanh iu à!',
    introDesc: `b_autiful đẹp hơn khi có e`,
    btnIntro: 'ỏ~~~',
    title: 'Phải chăng Nanh đã yêu Kiên 😙',
    desc: 'Phải chăng em đã say ngay từ lúc thấy nụ cười ấy ',
    btnYes: 'Sao biết hay thế <33',
    btnNo: 'Mơ à :3',
    question:'Trên thế giới hơn 7 tỉ người mà sao Nanh lại yêu Kiên <3',
    btnReply: 'Gửi cho Kiên <3',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Kiên biết mà 🥰. Yêu Nanh nhất 😘😘',
    messDesc: 'Sinh nhật vui vẻ nha công chúa ❤.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'http://fb.com' https://www.facebook.com/profile.php?id=100066933925753
